### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [chtixof/yunofav_ynh#5]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by chtixof** [comment]
Je me suis décidé à répondre aux demandes de transfert de mes applis Yunohost, mais je n'arrive pas à transférer celle-ci car sur Yunohost-Apps il existe une appli yunofav provenant d'un fork. Pouvez-vous m'indiquer ce que je dois faire pour la transférer ?

**Comment by frju365** [comment]
Quelle est l'URL de ce fork car je le vois pas ?

**Comment by chtixof** [comment]
Merci. @magikcypres_cyp a (fait) supprimer l'appli forkée pour que je puisse faire le transfert. Tutto va bene.

**Comment by frju365** [comment]
Content qu'il n'y a pas que moi qui fasse ce travail. ;) Merci à @magikcypress pour sa grande réactivité et merci à toi, @chtixof.
frju365
